# Generated by Django 4.2.6 on 2023-10-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_category_blogpost_published_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_at',
        ),
    ]
