# Generated by Django 4.2.6 on 2023-10-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_like_remove_blogpost_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
